#109: find specific languages when generics are specified
sillsdev/l10nsharp pull request #110
Opened 2023-03-03 23:15 UTC by papeh

If a client tries to initialize a LocalizationManager with only
a language code, and we have a language available with that code
plus extra information, use that language without prompting the user.

This addresses https://github.com/sillsdev/l10nsharp/issues/109
This addresses https://jira.sil.org/browse/LT-21232

2023-03-06 17:51 UTC, tombogle requested changes
I think you'll want an entry in CHANGELOG.md for this somewhat subtle change.

2023-03-06 17:57 UTC, tombogle commented
*[`src/L10NSharp/XLiffUtils/XLiffLocalizedStringCache.cs` line 179 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/110#-NPs3Ejk5Z1rN3OFsahI:-NPs3Ejk5Z1rN3OFsahJ:bw2f3x3) ([raw file](https://github.com/sillsdev/l10nsharp/blob/5aa9dbd4c71d7d317749b28a7fedcfa889ecff07/src/L10NSharp/XLiffUtils/XLiffLocalizedStringCache.cs#L179)):*
> ```Smalltalk
> 				// Another possibility is that the lang folder is "es-ES" but the client is requesting only "es".
> 				// TODO: actual implementation here:
> 				if (langId == "zz") return;
> ```

Although there is one exception, it seems our normal standard is to put the return on a line by itself. IMHO, that makes for more readable code. It's easy to miss the return at the end of the line when scanning through the code quickly.


<!-- Sent from Reviewable.io -->

2023-03-06 18:03 UTC, tombogle commented
*[`src/L10NSharp/XLiffUtils/XLiffLocalizedStringCache.cs` line 178 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/110#-NPs4aSfBvmO4jO_l0NL:-NPs4aSg8H7qw6Vs0lLc:bcbqekp) ([raw file](https://github.com/sillsdev/l10nsharp/blob/5aa9dbd4c71d7d317749b28a7fedcfa889ecff07/src/L10NSharp/XLiffUtils/XLiffLocalizedStringCache.cs#L178)):*
> ```Smalltalk
> 					return;
> 				// Another possibility is that the lang folder is "es-ES" but the client is requesting only "es".
> 				// TODO: actual implementation here:
> ```

Can you expand on what this TODO is about? I'm guessing the idea is that someday we might know of specific language tag for which we can do something better than just give up. Is that the idea?


<!-- Sent from Reviewable.io -->

2023-03-06 18:07 UTC, tombogle commented
*[`src/L10NSharpTests/LocalizationManagerTestsBase.cs` line 438 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/110#-NPs5mCcA_OI4IUut0tl:-NPs5mCcA_OI4IUut0tm:b-kdd6rm) ([raw file](https://github.com/sillsdev/l10nsharp/blob/5aa9dbd4c71d7d317749b28a7fedcfa889ecff07/src/L10NSharpTests/LocalizationManagerTestsBase.cs#L438)):*
> ```Smalltalk
> 		[TestCase(new[] { "en" }, "blahInEnglishCode", "en", TestName = "en; finds en")]
> 		[TestCase(new[] { "en", "fr" }, "blahInEnglishCode", "en", TestName = "en,fr; finds en")]
> 		[TestCase(new[] { "ar", "en" }, "blahInEnglishCode", "en", TestName = "ar,en; finds en")] // our arabic doesn't have a translation of 'blah', so fall to the code's English
> ```

Not your fault, but this should say "fall back"


<!-- Sent from Reviewable.io -->

2023-03-06 18:13 UTC, tombogle commented
*[`src/L10NSharpTests/LocalizationManagerTestsBase.cs` line 581 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/110#-NPs6Yb29rQPPf1eyl3k:-NPs6Yb34YrEyBnHX2vT:b-5gqjju) ([raw file](https://github.com/sillsdev/l10nsharp/blob/5aa9dbd4c71d7d317749b28a7fedcfa889ecff07/src/L10NSharpTests/LocalizationManagerTestsBase.cs#L581)):*
> ```Smalltalk
> 		}
> 
> 		private void AddChineseChineseTranslation(string folderPath)
> ```

Not sure I understand the purpose of having Chinese twicetwice in the method name. zh-CN is Simplified Chinese as used in China. Perhaps the name should be AddSimplifiedChineseTranslation OR AddSimplifiedChineseOfChinaTranslation OR AddChineseOfChinaTranslation OR AddZhCnChineseTranslation OR AddChineseZhCnTranslation OR AddChineseTranslation.


<!-- Sent from Reviewable.io -->

2023-03-06 18:35 UTC, tombogle commented
*[`src/L10NSharpTests/XLiffLocalizedStringCacheTests.cs` line 86 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/110#-NPsC7Fk85i0f05THMjs:-NPsC7Fl5djE6BH5m2y7:b38udxe) ([raw file](https://github.com/sillsdev/l10nsharp/blob/5aa9dbd4c71d7d317749b28a7fedcfa889ecff07/src/L10NSharpTests/XLiffLocalizedStringCacheTests.cs#L86)):*
> ```Smalltalk
> 		public void TryGetDocument()
> 		{
> 			//var sut = new XLiffLocalizedStringCache();
> ```

Is this unfinished work, or something that needs to be reverted?


<!-- Sent from Reviewable.io -->

2023-03-06 18:35 UTC, tombogle reviewed
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/110)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @papeh)



<!-- Sent from Reviewable.io -->

2023-03-06 22:16 UTC, papeh reviewed
> Dismissed @tombogle from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/110)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @papeh and @tombogle)

___
*[`src/L10NSharp/XLiffUtils/XLiffLocalizedStringCache.cs` line 178 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/110#-NPs4aSfBvmO4jO_l0NL:-NPsu7kM76ETjD9x8fZL:b3tar7t) ([raw file](https://github.com/sillsdev/l10nsharp/blob/5aa9dbd4c71d7d317749b28a7fedcfa889ecff07/src/L10NSharp/XLiffUtils/XLiffLocalizedStringCache.cs#L178)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Can you expand on what this TODO is about? I'm guessing the idea is that someday we might know of specific language tag for which we can do something better than just give up. Is that the idea?
</blockquote></details>

I plan to implement the behaviour for the remaining cases before removing this PR's draft status.
___
*[`src/L10NSharp/XLiffUtils/XLiffLocalizedStringCache.cs` line 179 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/110#-NPs3Ejk5Z1rN3OFsahI:-NPstwVm3lAHApUeY1tG:b-u39x5x) ([raw file](https://github.com/sillsdev/l10nsharp/blob/5aa9dbd4c71d7d317749b28a7fedcfa889ecff07/src/L10NSharp/XLiffUtils/XLiffLocalizedStringCache.cs#L179)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Although there is one exception, it seems our normal standard is to put the return on a line by itself. IMHO, that makes for more readable code. It's easy to miss the return at the end of the line when scanning through the code quickly.
</blockquote></details>

That line was temporary. It has been removed.
___
*[`src/L10NSharpTests/LocalizationManagerTestsBase.cs` line 438 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/110#-NPs5mCcA_OI4IUut0tl:-NPsujCA0B8vnJMrcb7Q:b-d7bhn0) ([raw file](https://github.com/sillsdev/l10nsharp/blob/5aa9dbd4c71d7d317749b28a7fedcfa889ecff07/src/L10NSharpTests/LocalizationManagerTestsBase.cs#L438)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Not your fault, but this should say "fall back"
</blockquote></details>

will do
___
*[`src/L10NSharpTests/LocalizationManagerTestsBase.cs` line 581 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/110#-NPs6Yb29rQPPf1eyl3k:-NPsuga_BqZ-_76jLx9I:bgvs52y) ([raw file](https://github.com/sillsdev/l10nsharp/blob/5aa9dbd4c71d7d317749b28a7fedcfa889ecff07/src/L10NSharpTests/LocalizationManagerTestsBase.cs#L581)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Not sure I understand the purpose of having Chinese twicetwice in the method name. zh-CN is Simplified Chinese as used in China. Perhaps the name should be AddSimplifiedChineseTranslation OR AddSimplifiedChineseOfChinaTranslation OR AddChineseOfChinaTranslation OR AddZhCnChineseTranslation OR AddChineseZhCnTranslation OR AddChineseTranslation.
</blockquote></details>

will do.
___
*[`src/L10NSharpTests/LocalizationManagerTestsBase.cs` line 987 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/110#-NPs9IcxE6exdm8InWOK:-NPszIgSEKJ9huUm2gwO:bq92tas) ([raw file](https://github.com/sillsdev/l10nsharp/blob/5aa9dbd4c71d7d317749b28a7fedcfa889ecff07/src/L10NSharpTests/LocalizationManagerTestsBase.cs#L987)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

I know you said you intended to leaved "undefined" the behavior when "zn" is requested, but multiple zn- variants are available. Specifically in the case of "zn", I'm not sure this is a good idea. I don't know when/where we expect an application to request "zn", but I think it will be very common that if there is an available "zn-" language, there will be at least two. If it is truly impossible to decide upon a defined order of precedence, then I can't think of a benefit of implementing this behavior. If a caller can't know what to expect, why would they call the method?
</blockquote></details>

How about I add a test that it returns a match only if there is exactly one?
___
*[`src/L10NSharpTests/XLiffLocalizedStringCacheTests.cs` line 86 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/110#-NPsC7Fk85i0f05THMjs:-NPszeTG2FOPW8JMzA0X:bj1nvfx) ([raw file](https://github.com/sillsdev/l10nsharp/blob/5aa9dbd4c71d7d317749b28a7fedcfa889ecff07/src/L10NSharpTests/XLiffLocalizedStringCacheTests.cs#L86)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Is this unfinished work, or something that needs to be reverted?
</blockquote></details>

unfinished work.


<!-- Sent from Reviewable.io -->

2023-03-06 22:21 UTC, papeh reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/110)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @tombogle)

___
*[`src/L10NSharpTests/LocalizationManagerTestsBase.cs` line 987 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/110#-NPs9IcxE6exdm8InWOK:-NPt-_tMEyK_Yk-H9ts4:brvwnzm) ([raw file](https://github.com/sillsdev/l10nsharp/blob/5aa9dbd4c71d7d317749b28a7fedcfa889ecff07/src/L10NSharpTests/LocalizationManagerTestsBase.cs#L987)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

How about I add a test that it returns a match only if there is exactly one?
</blockquote></details>

(FieldWorks ships only zh-CN, because some systems (Mono and historically Windows) do not recognize `zh` on its own.


<!-- Sent from Reviewable.io -->

2023-03-07 14:56 UTC, tombogle commented
*[`src/L10NSharpTests/LocalizationManagerTestsBase.cs` line 987 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/110#-NPs9IcxE6exdm8InWOK:-NPwZWyq5t1v6ludaz35:b-9s9gz0) ([raw file](https://github.com/sillsdev/l10nsharp/blob/5aa9dbd4c71d7d317749b28a7fedcfa889ecff07/src/L10NSharpTests/LocalizationManagerTestsBase.cs#L987)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

(FieldWorks ships only zh-CN, because some systems (Mono and historically Windows) do not recognize `zh` on its own.
</blockquote></details>

I think that seems like a reasonable implementation (at least until we can find something more reasonable to do in some case).


<!-- Sent from Reviewable.io -->

2023-03-07 15:22 UTC, papeh reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/110)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @tombogle)

___
*[`src/L10NSharpTests/LocalizationManagerTestsBase.cs` line 438 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/110#-NPs5mCcA_OI4IUut0tl:-NPt6QIc5_u5IgPREKzm:b-896fix) ([raw file](https://github.com/sillsdev/l10nsharp/blob/5aa9dbd4c71d7d317749b28a7fedcfa889ecff07/src/L10NSharpTests/LocalizationManagerTestsBase.cs#L438)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

will do
</blockquote></details>

Done.
___
*[`src/L10NSharpTests/LocalizationManagerTestsBase.cs` line 581 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/110#-NPs6Yb29rQPPf1eyl3k:-NPt6TGE-YV4bQ1NJ4UI:b-896fix) ([raw file](https://github.com/sillsdev/l10nsharp/blob/5aa9dbd4c71d7d317749b28a7fedcfa889ecff07/src/L10NSharpTests/LocalizationManagerTestsBase.cs#L581)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

will do.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-07 22:58 UTC, papeh reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/110)* status: 0 of 14 files reviewed, 5 unresolved discussions (waiting on @tombogle)

___
*[`src/L10NSharpTests/XLiffLocalizedStringCacheTests.cs` line 86 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/110#-NPsC7Fk85i0f05THMjs:-NPyHlLHD5D8fFPwG6pI:bjiwfnb) ([raw file](https://github.com/sillsdev/l10nsharp/blob/5aa9dbd4c71d7d317749b28a7fedcfa889ecff07/src/L10NSharpTests/XLiffLocalizedStringCacheTests.cs#L86)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

unfinished work.
</blockquote></details>

this part of XLiffLocalizedStringCache is easier to test in LocalizationManagerTestsBase


<!-- Sent from Reviewable.io -->

2023-03-08 03:53 UTC, tombogle commented
*[`CHANGELOG.md` line 23 at r6](https://reviewable.io/reviews/sillsdev/l10nsharp/110#-NPzK6qh5rU9J9h3JQAI:-NPzK6qh5rU9J9h3JQAJ:b-yjn4f3) ([raw file](https://github.com/sillsdev/l10nsharp/blob/a833f7dce1e4ee707b4ecd40fdf9222fc368279b/CHANGELOG.md#L23)):*
> ```Markdown
> - `LocalizationManager.Create` methods without `TranslationMemory kind` parameter
> 
> ### Fixed
> ```

Even if no public members were changed, I wonder if we want this to be regarded as a "fix" or a "change"? Not 100% sure that these changes wouldn't be in some sense "breaking", given the new behavior. Hopefully not, but it's hard to be sure.


<!-- Sent from Reviewable.io -->

2023-03-08 03:57 UTC, tombogle commented
*[`L10NSharp.sln.DotSettings` line 7 at r6](https://reviewable.io/reviews/sillsdev/l10nsharp/110#-NPzM7ku-3tXhPu-NMbN:-NPzM7ku-3tXhPu-NMbO:b-f3ocv5) ([raw file](https://github.com/sillsdev/l10nsharp/blob/a833f7dce1e4ee707b4ecd40fdf9222fc368279b/L10NSharp.sln.DotSettings#L7)):*
> ```
> 	<s:Boolean x:Key="/Default/UserDictionary/Words/=Filenames/@EntryIndexedValue">True</s:Boolean>
> 	<s:Boolean x:Key="/Default/UserDictionary/Words/=langs/@EntryIndexedValue">True</s:Boolean>
> 	<s:Boolean x:Key="/Default/UserDictionary/Words/=Liff/@EntryIndexedValue">True</s:Boolean>
> ```

I had considered doing this at one point, but since Liff isn't really a word and the miscapitalization is something that probably "should" be fixed if it weren't so entrenched, I kind of wondered if it was maybe better to just let it keep complaining.


<!-- Sent from Reviewable.io -->

2023-03-08 04:11 UTC, tombogle reviewed
Just a few outstanding questions to ponder. Otherwise, LGTM. Since a lot of projects depend on this, might not be all bad to get another set of eyes to review it, maybe someone from the Bloom team. 

> Reviewed 2 of 4 files at r4, 3 of 12 files at r5, 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/110#-:-NPzPG0sCQqw4Ic_Dk_I:b-y1t6rt)* status: all files reviewed, 2 unresolved discussions (waiting on @papeh)



<!-- Sent from Reviewable.io -->

2023-03-08 17:00 UTC, papeh reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/110)* status: 5 of 14 files reviewed, 2 unresolved discussions (waiting on @tombogle)

___
*[`CHANGELOG.md` line 23 at r6](https://reviewable.io/reviews/sillsdev/l10nsharp/110#-NPzK6qh5rU9J9h3JQAI:-NQ0t1yzESIJwsMZKHSU:b-i0lt1c) ([raw file](https://github.com/sillsdev/l10nsharp/blob/a833f7dce1e4ee707b4ecd40fdf9222fc368279b/CHANGELOG.md#L23)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Even if no public members were changed, I wonder if we want this to be regarded as a "fix" or a "change"? Not 100% sure that these changes wouldn't be in some sense "breaking", given the new behavior. Hopefully not, but it's hard to be sure.
</blockquote></details>

Yes, it breaks the behaviour where creating a manager for "es" when only "es-ES" is available results in a user prompt. The only documentation I found (comment on LocalizationManagerInternal<T>.MapToExistingLanguageIfPossible) says that the post-PR behaviour is correct (at least after es-ES has been loaded).
___
*[`L10NSharp.sln.DotSettings` line 7 at r6](https://reviewable.io/reviews/sillsdev/l10nsharp/110#-NPzM7ku-3tXhPu-NMbN:-NQ19HexDixhhdjum2IL:b-ldwsbj) ([raw file](https://github.com/sillsdev/l10nsharp/blob/a833f7dce1e4ee707b4ecd40fdf9222fc368279b/L10NSharp.sln.DotSettings#L7)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

I had considered doing this at one point, but since Liff isn't really a word and the miscapitalization is something that probably "should" be fixed if it weren't so entrenched, I kind of wondered if it was maybe better to just let it keep complaining.
</blockquote></details>

I was about to fix them, but so many are public, and I couldn't be bothered to deprecate them and set up aliases.


<!-- Sent from Reviewable.io -->

2023-03-13 21:12 UTC, merged