Make lazy loading of xliffs thread-safe (BL-11086)
sillsdev/l10nsharp pull request #93
Opened 2022-04-04 17:04 UTC by JohnThomson

Also makes all methods consistently handle fall-back from e.g. es-BR to es-ES.

2022-04-04 20:33 UTC, andrew-polk requested changes
LGTM (besides a minor existing issue I brought up), but I think another set of eyes would be beneficial.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/93#-:-MzqGwCHAatsoQmXyomw:bythwps)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/L10NSharp/LocalizationManagerInternal.cs, line 96 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/93#-MzpvkGF1EuWaBZyMzXa:-MzpvkGGA29djhedpiO9:b-f9uedd) ([raw file](https://github.com/sillsdev/l10nsharp/blob/12f13a957b95faa0dc3eb1de0ab3499dbc260c61/src/L10NSharp/LocalizationManagerInternal.cs#L96)):*
> ```Smalltalk
> 			var fallbackLangId = MapToExistingLanguageIfPossible(desiredUiLangId);
> 			if (fallbackLangId == desiredUiLangId)
> 				return false; // identity mappings don't give us new options, and could lead to stack overflow
> ```

I see you didn't change the logic here, but it is counterintuitive for something called `IsDesiredUiCultureAvailable` to return false just because we didn't have to map it to anything.
Is it actually true that we should never get here because we would have returned true three lives above? If so, we should probably add that to the comment.


<!-- Sent from Reviewable.io -->

2022-04-04 22:36 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/93)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/L10NSharp/LocalizationManagerInternal.cs, line 96 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/93#-MzpvkGF1EuWaBZyMzXa:-MzqiCrL76qaDj9FvhCu:bbza80c) ([raw file](https://github.com/sillsdev/l10nsharp/blob/12f13a957b95faa0dc3eb1de0ab3499dbc260c61/src/L10NSharp/LocalizationManagerInternal.cs#L96)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I see you didn't change the logic here, but it is counterintuitive for something called `IsDesiredUiCultureAvailable` to return false just because we didn't have to map it to anything.
Is it actually true that we should never get here because we would have returned true three lives above? If so, we should probably add that to the comment.
</blockquote></details>

I hope it's clear now.


<!-- Sent from Reviewable.io -->

2022-04-04 22:42 UTC, andrew-polk approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/93)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)



<!-- Sent from Reviewable.io -->

2022-04-05 18:01 UTC, tombogle reviewed
LGTM. Is there a good way to write a unit test or two that can ensure that this is correct?

2022-04-05 23:07 UTC, jasonleenaylor reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/93)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/L10NSharp/LocalizationManagerInternal.cs, line 104 at r2](https://reviewable.io/reviews/sillsdev/l10nsharp/93#-MzuhADLCFIih4QkJY5M:-MzuhADLCFIih4QkJY5N:b-3qmx4i) ([raw file](https://github.com/sillsdev/l10nsharp/blob/c83df1fb3861883b4849a9da8086dbb46174155b/src/L10NSharp/LocalizationManagerInternal.cs#L104)):*
> ```Smalltalk
> 			// localization. In such a case, if we don't detect it, we'd be making a recursive call
> 			// with the same argument, which would produce stack overflow. So if we didn't find
> 			// a different language to try, we must fail now.
> ```

John, this comment very accurately captures the situation and is certainly more helpful to understanding than the original comment, but it is also more likely to generate a tldr; response.

Imagining myself maintaining this code I think only the details about our usage in this context is necessary. e.g. Why do we return false on this condition?

I'd sum this up as:
// If the input and output of MapToExistingLanguageIfPossible are the same then there is no mapping known for the language and we should return false instead of infinitely recursing.

Feel free to come up with your own summary, but try to limit your creative writing to two or three lines.



_Code quote:_
```Smalltalk
			// However, MapToExistingLanguageIfPossible often returns the code we started with.
			// This can indicate that we don't need to map it since we have exactly that localization,
			// but in such a case, IsLocalizationAvailable would have returned true above and we would
			// not get here. However, it also returns an unchanged code for a locale about which we
			// know nothing at all...there is no closely related language for which we have a
			// localization. In such a case, if we don't detect it, we'd be making a recursive call
			// with the same argument, which would produce stack overflow. So if we didn't find
			// a different language to try, we must fail now.
```
___
*[src/L10NSharp/LocalizationManagerInternal.cs, line 694 at r2](https://reviewable.io/reviews/sillsdev/l10nsharp/93#-MzukPxzDn2b-hpJunf8:-MzukPxzDn2b-hpJunf9:bcpsh5u) ([raw file](https://github.com/sillsdev/l10nsharp/blob/c83df1fb3861883b4849a9da8086dbb46174155b/src/L10NSharp/LocalizationManagerInternal.cs#L694)):*
> ```Smalltalk
> 
> 
> 				var pieces = langId.Split('-');
> ```

Move this after the comment to help clarify the comment.



_Code quote:_
```Smalltalk
var pieces = langId.Split('-');
```


<!-- Sent from Reviewable.io -->

2022-04-06 06:53 UTC, ermshiperete approved these changes

2022-04-06 17:54 UTC, JohnThomson reviewed
I'm open to ideas. For the most part, I've made things concurrent by using .NET ConcurrentDictionary. Assuming that works correctly, there should not be much danger of race conditions; and I don't believe anything I've changed holds a lock for more than the duration of a single call, nor while calling back to unknown code, nor ever holds more than one lock at a time; so I don't think I've created a danger of deadlocks. I'm hoping the existing unit tests cover what I've changed pretty well

> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/93#-:-MzzyR3i2M8LxzytRYez:b2la29l)* status: 1 of 9 files reviewed, all discussions resolved (waiting on @andrew-polk and @jasonleenaylor)

___
*[src/L10NSharp/LocalizationManagerInternal.cs, line 104 at r2](https://reviewable.io/reviews/sillsdev/l10nsharp/93#-MzuhADLCFIih4QkJY5M:-N---u0s7QpX6BOMWvfI:bb7f2mf) ([raw file](https://github.com/sillsdev/l10nsharp/blob/c83df1fb3861883b4849a9da8086dbb46174155b/src/L10NSharp/LocalizationManagerInternal.cs#L104)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

John, this comment very accurately captures the situation and is certainly more helpful to understanding than the original comment, but it is also more likely to generate a tldr; response.

Imagining myself maintaining this code I think only the details about our usage in this context is necessary. e.g. Why do we return false on this condition?

I'd sum this up as:
// If the input and output of MapToExistingLanguageIfPossible are the same then there is no mapping known for the language and we should return false instead of infinitely recursing.

Feel free to come up with your own summary, but try to limit your creative writing to two or three lines.

</blockquote></details>

done
___
*[src/L10NSharp/LocalizationManagerInternal.cs, line 694 at r2](https://reviewable.io/reviews/sillsdev/l10nsharp/93#-MzukPxzDn2b-hpJunf8:-N---qtVBU5sGDGfKBRH:bb7f2mf) ([raw file](https://github.com/sillsdev/l10nsharp/blob/c83df1fb3861883b4849a9da8086dbb46174155b/src/L10NSharp/LocalizationManagerInternal.cs#L694)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Move this after the comment to help clarify the comment.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-04-06 17:57 UTC, JohnThomson reviewed
I don't know how to write unit tests specifically for thread-safety.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/93#-:-N--0T4s5buz0pYT4Kei:b-pn2620)* status: 1 of 9 files reviewed, all discussions resolved (waiting on @andrew-polk and @jasonleenaylor)



<!-- Sent from Reviewable.io -->

2022-04-06 19:13 UTC, tombogle requested changes

2022-04-06 19:13 UTC, tombogle commented on src/L10NSharp/XLiffUtils/XLiffBody.cs
> +		/// into it, which does not work with the current version. The List wrapper implements just
ListWrapper

2022-04-06 19:54 UTC, tombogle commented on src/L10NSharp/XLiffUtils/XLiffBody.cs
> +		/// mainly for backwards compatibility.
Since the behavior is subtly changing, maybe trying to preserve "backwards compatibility" is a bad thing.

2022-04-07 06:33 UTC, ermshiperete requested changes
This PR deserves an entry in `CHANGELOG.md` :smile:

2022-04-07 20:11 UTC, JohnThomson reviewed
Done

> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/93#-:-N-4cF459HA5fdVyu8bJ:bb6un1j)* status: 1 of 12 files reviewed, 2 unresolved discussions (waiting on @andrew-polk, @jasonleenaylor, and @tombogle)

___
*[src/L10NSharp/XLiffUtils/XLiffBody.cs, line 76 at r5](https://reviewable.io/reviews/sillsdev/l10nsharp/93#-MzzweOukyNNXkbDWXkU-r5-76:-N-4dact1yx4Hyi1WGii:b-8qt6ii) ([raw file](https://github.com/sillsdev/l10nsharp/blob/86f91a710b4c6f15f1c080b31abee8e5eec8d9f0/src/L10NSharp/XLiffUtils/XLiffBody.cs#L76)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Since the behavior is subtly changing, maybe trying to preserve "backwards compatibility" is a bad thing.
</blockquote></details>

Following your suggestion in Slack, I decided to remove it completely, making it a clearly breaking change, though unlikely to break most clients.
___
*[src/L10NSharp/XLiffUtils/XLiffBody.cs, line 105 at r5](https://reviewable.io/reviews/sillsdev/l10nsharp/93#-MzzweOukyNNXkbDWXkU-r5-105:-N-4dftv0lM2DqRk3_eY:b-896fix) ([raw file](https://github.com/sillsdev/l10nsharp/blob/86f91a710b4c6f15f1c080b31abee8e5eec8d9f0/src/L10NSharp/XLiffUtils/XLiffBody.cs#L105)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

ListWrapper
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-08 07:04 UTC, ermshiperete approved these changes
A few nitpicks in `CHANGELOG.md`, but otherwise :lgtm:

2022-04-08 13:09 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/93)* status: 1 of 12 files reviewed, 5 unresolved discussions (waiting on @andrew-polk, @ermshiperete, @jasonleenaylor, and @tombogle)

___
*[CHANGELOG.md, line 25 at r7](https://reviewable.io/reviews/sillsdev/l10nsharp/93#-N-4c6yrA3ZSSvKbhgsV-r7-25:-N-8HFrG35fV9vdVKWvH:b-896fix) ([raw file](https://github.com/sillsdev/l10nsharp/blob/6be6ac18917df11bfd7b63919e577dc758030bb4/CHANGELOG.md#L25)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

This should go in the (new) `### Removed` section
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 27 at r7](https://reviewable.io/reviews/sillsdev/l10nsharp/93#-N-4c6yrA3ZSSvKbhgsV-r7-27:-N-8HHHtD93lTsR9TVSv:b-896fix) ([raw file](https://github.com/sillsdev/l10nsharp/blob/6be6ac18917df11bfd7b63919e577dc758030bb4/CHANGELOG.md#L27)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

The three "added" topics should go in the `### Added` section
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 30 at r7](https://reviewable.io/reviews/sillsdev/l10nsharp/93#-N-4c6yrA3ZSSvKbhgsV-r7-30:-N-8HO2V3EmU__GtmmSD:b-p1343i) ([raw file](https://github.com/sillsdev/l10nsharp/blob/6be6ac18917df11bfd7b63919e577dc758030bb4/CHANGELOG.md#L30)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

```suggestion
  serialization and deserialization in XML, but is not intended for any other purpose.
```
</blockquote></details>

I 'm thinking you just wanted this indented?


<!-- Sent from Reviewable.io -->

2022-04-08 14:50 UTC, jasonleenaylor reviewed
> Reviewed 1 of 7 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/93)* status: 3 of 12 files reviewed, 5 unresolved discussions (waiting on @andrew-polk, @ermshiperete, @jasonleenaylor, and @tombogle)

___
*[src/L10NSharp/LocalizationManagerInternal.cs, line 104 at r2](https://reviewable.io/reviews/sillsdev/l10nsharp/93#-MzuhADLCFIih4QkJY5M:-N--04a_ATtQHLzTMefX:b-8fx2u7) ([raw file](https://github.com/sillsdev/l10nsharp/blob/c83df1fb3861883b4849a9da8086dbb46174155b/src/L10NSharp/LocalizationManagerInternal.cs#L104)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

done
</blockquote></details>

:+1: 


<!-- Sent from Reviewable.io -->

2022-04-09 09:51 UTC, ermshiperete approved these changes

2022-04-09 09:53 UTC, ermshiperete approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 7 files at r3, 2 of 3 files at r5, 1 of 3 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/93#-:-N-CjXy83LQ2-z2nPbOG:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @tombogle)

___
*[CHANGELOG.md, line 30 at r7](https://reviewable.io/reviews/sillsdev/l10nsharp/93#-N-4c6yrA3ZSSvKbhgsV-r7-30:-N-CjR7IAa1r9muuVh5N:bb7sa0c) ([raw file](https://github.com/sillsdev/l10nsharp/blob/6be6ac18917df11bfd7b63919e577dc758030bb4/CHANGELOG.md#L30)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I 'm thinking you just wanted this indented?
</blockquote></details>

yes.


<!-- Sent from Reviewable.io -->

2022-04-12 19:34 UTC, merged