Add flag to avoid progress dialogs for xliff initialization
sillsdev/l10nsharp pull request #95
Opened 2022-05-16 21:26 UTC by StephenMcConnel

This was discussed at the conference.  I think this is the minimal
change to the code that allows current behavior for programs that may
still benefit from it.

2022-05-16 21:49 UTC, andrew-polk reviewed
Code changes look ok.
But I've (re?)opened a discussion in Slack re: whether we can't just remove the dialogs altogether.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/95#-:-N2DpzQ4D6D-c4mrazqb:b-nmfyne)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)



<!-- Sent from Reviewable.io -->

2022-05-16 22:05 UTC, andrew-polk requested changes
Sorry; one more thing. For following strict semver, we need +semver:minor in the commit message.
And we also want to add a statement to CHANGELOG.md.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/95#-:-N2DtYy_Avkewzi6ycJN:b-ru2bdn)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)



<!-- Sent from Reviewable.io -->

2022-05-16 23:03 UTC, StephenMcConnel reviewed
I've added the +semver:minor and a statement to CHANGELOG.md.  But this probably does need to wait for further discussion in slack about the extent of the change.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/95#-:-N2E5uCuAxo5tCBu3AJN:b-jgburz)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)



<!-- Sent from Reviewable.io -->

2022-05-16 23:19 UTC, andrew-polk approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/95)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)



<!-- Sent from Reviewable.io -->

2022-05-17 16:10 UTC, StephenMcConnel reviewed
John Hatton pointed out that the decision was made at the conference to just remove the progress dialog, so I've amended the PR to unconditionally do that for Xliff initialization.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/95#-:-N2Hm-4Q9kIdzl-dBtbd:b3xkr4j)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @andrew-polk)



<!-- Sent from Reviewable.io -->

2022-05-17 17:22 UTC, andrew-polk approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/95)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)



<!-- Sent from Reviewable.io -->

2022-05-17 18:47 UTC, tombogle commented
*[`src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs` line 209 at r3](https://reviewable.io/reviews/sillsdev/l10nsharp/95#-N2IL7tx79kKvR1Zo_3G:-N2IL7tx79kKvR1Zo_3H:bu6t9ve) ([raw file](https://github.com/sillsdev/l10nsharp/blob/44f8136568c09f357adf1c6a068e3be14c72beda/src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs#L209)):*
> ```Smalltalk
> 			var stringCache = new XLiffLocalizedStringCache(this, false);
> 
> 			var extractedInfo = ExtractStringsWIthoutDialog(Name, additionalLocalizationMethods, namespaceBeginnings);
> ```

Not sure if "WithoutDialog" is particularly meaningful if there is NEVER a dialog.


<!-- Sent from Reviewable.io -->

2022-05-17 23:21 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/95)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @tombogle)

___
*[`CHANGELOG.md` line 21 at r3](https://reviewable.io/reviews/sillsdev/l10nsharp/95#-N2I2-yTEfp-T0B3ZaJL:-N2JHfBC542AVHVV90dG:b8za6t1) ([raw file](https://github.com/sillsdev/l10nsharp/blob/44f8136568c09f357adf1c6a068e3be14c72beda/CHANGELOG.md#L21)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We should probably move this to the changed or removed section now.
</blockquote></details>

Done.  Moved to the Changed section.
___
*[`src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs` line 209 at r3](https://reviewable.io/reviews/sillsdev/l10nsharp/95#-N2IL7tx79kKvR1Zo_3G:-N2JHlnUBE83OU_8eEnT:b80hlgc) ([raw file](https://github.com/sillsdev/l10nsharp/blob/44f8136568c09f357adf1c6a068e3be14c72beda/src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs#L209)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Not sure if "WithoutDialog" is particularly meaningful if there is NEVER a dialog.
</blockquote></details>

Done.  Renamed to ExtractStringsFromCode
___
*[`src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs` line 230 at r3](https://reviewable.io/reviews/sillsdev/l10nsharp/95#-N2I26yZEP1uHMTMKUmd:-N2JHqDu6tPoSCYM20a0:blmnzwk) ([raw file](https://github.com/sillsdev/l10nsharp/blob/44f8136568c09f357adf1c6a068e3be14c72beda/src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs#L230)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

ExtractStringsWithoutDialog
(lowercase i)
since you're making a change anyway
</blockquote></details>

Renamed method to ExtractStringsFromCode, being more careful about capitalization.  :-)


<!-- Sent from Reviewable.io -->

2022-05-17 23:42 UTC, andrew-polk approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/95)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)



<!-- Sent from Reviewable.io -->

2022-05-17 23:43 UTC, merged